### PR TITLE
prevents user without editor access to publish article which fixes #576

### LINKED ISSUE #576: Prevent writers to publish articles
I think publishing of articles should only be given to editors. Users with writers permission should not be given the permission to publish. This follows the way many publishing site works. 

If such feature does not already exist, I think it should be considered.

### PR DESCRIPTION
**Pull request by JahlomP**

### CODE REVIEW

**Comment by brianhyder** [comment]
These controllers are deprecated as of 0.5.0.  We are going to decline this PR because the changes will just be removed in the next version.  If this is still an issue in 0.5.0 then we would need to include a validation in the ArticleServiceV2 prototype.

**Comment by JahlomP** [comment]
OK

On Thu, Nov 12, 2015 at 1:48 AM Brian <notifications@github.com> wrote:

> These controllers are deprecated as of 0.5.0. We are going to decline this
> PR because the changes will just be removed in the next version. If this is
> still an issue in 0.5.0 then we would need to include a validation in the
> ArticleServiceV2 prototype.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/pull/809#issuecomment-155971071>
> .
>
-- 
Best Rregards,
Precious Jahlom Agboado,
www.twitter.com/jahlomp
+233 54 0915 108.

**Comment by JahlomP** [comment]
Should I be focusing on 0.5.0?

On Thu, Nov 12, 2015 at 9:27 AM Jahlom Agboado <jahlomp@gmail.com> wrote:

> OK
>
> On Thu, Nov 12, 2015 at 1:48 AM Brian <notifications@github.com> wrote:
>
>> These controllers are deprecated as of 0.5.0. We are going to decline
>> this PR because the changes will just be removed in the next version. If
>> this is still an issue in 0.5.0 then we would need to include a validation
>> in the ArticleServiceV2 prototype.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/pencilblue/pencilblue/pull/809#issuecomment-155971071>
>> .
>>
> --
> Best Rregards,
> Precious Jahlom Agboado,
> www.twitter.com/jahlomp
> +233 54 0915 108.
>
-- 
Best Rregards,
Precious Jahlom Agboado,
www.twitter.com/jahlomp
+233 54 0915 108.

**Comment by brianhyder** [comment]
Correct, any changes to the platform (except for major bug fixes) should go
into 0.5.0.

**Comment by JahlomP** [comment]
OK

On Thu, Nov 12, 2015 at 11:11 AM Brian <notifications@github.com> wrote:

> Correct, any changes to the platform (except for major bug fixes) should go
> into 0.5.0.
> On Nov 12, 2015 4:28 AM, "Precious Jahlom Agboado" <
> notifications@github.com>
> wrote:
>
> > Should I be focusing on 0.5.0?
> >
> > On Thu, Nov 12, 2015 at 9:27 AM Jahlom Agboado <jahlomp@gmail.com>
> wrote:
> >
> > > OK
> > >
> > > On Thu, Nov 12, 2015 at 1:48 AM Brian <notifications@github.com>
> wrote:
> > >
> > >> These controllers are deprecated as of 0.5.0. We are going to decline
> > >> this PR because the changes will just be removed in the next version.
> If
> > >> this is still an issue in 0.5.0 then we would need to include a
> > validation
> > >> in the ArticleServiceV2 prototype.
> > >>
> > >> —
> > >> Reply to this email directly or view it on GitHub
> > >> <
> > https://github.com/pencilblue/pencilblue/pull/809#issuecomment-155971071
> >
> > >> .
> > >>
> > > --
> > > Best Rregards,
> > > Precious Jahlom Agboado,
> > > www.twitter.com/jahlomp
> > > +233 54 0915 108.
> > >
> > --
> > Best Rregards,
> > Precious Jahlom Agboado,
> > www.twitter.com/jahlomp
> > +233 54 0915 108.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/pencilblue/pencilblue/pull/809#issuecomment-156045736>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pencilblue/pencilblue/pull/809#issuecomment-156076081>
> .
>
-- 
Best Rregards,
Precious Jahlom Agboado,
www.twitter.com/jahlomp
+233 54 0915 108.

**Pull request closed without merging**
