### PR TITLE
added feature 464

### PR DESCRIPTION
**Pull request by JahlomP**
added feature 464

### CODE REVIEW

**Comment by blakecallens** [comment]
This is looking much better. We'll just need a couple more things before a merge:

1. We need a GENERATED key added to the localization.
2. The portfolio theme has an alternate page template. We'll need the generate url functionality there too.

Almost there!

**Comment by JahlomP** [comment]
K

**Comment by JahlomP** [comment]
done

**Comment by blakecallens** [comment]
Approved for merging, @brianhyder.

**Pull request merged**
