### PR TITLE
Fixes plugin dialog modal behaviour

### PR DESCRIPTION
**Pull request by dukeofsussex**
Fixes the progress modal closing down early and not showing the whole job log

- [x] Unit tests created and pass
- [x] JS Docs have been updated

**Description:**
TL;DR I messed up 😞 

@pencilblue/owners

### CODE REVIEW

**Comment by brianhyder** [comment]
Why would the greater than our equal too make a difference?

**Comment by dukeofsussex** [comment]
What equal to?

**Comment by brianhyder** [comment]
I don't understand how the change fixes the problem. Can you explain a
little bit?

**Comment by dukeofsussex** [comment]
Sure, so here's what was going wrong:

Backend:

- Trying to install plugin
- `isInstalled` check passes fine
- `PluginAvailableJob`
    - https://github.com/pencilblue/pencilblue/blob/master/include/service/jobs/plugins/plugin_available_job.js#L51
        - Calls `self.onUpdate(increment)` with `increment = 0`
    - https://github.com/pencilblue/pencilblue/blob/master/include/service/jobs/job_runner.js#L235
        - Increment = 0, so our `updates` object is still empty
        - Status is empty, so our `updates` object is still empty
    - https://github.com/pencilblue/pencilblue/blob/master/include/service/jobs/job_runner.js#L248
        - `updates` is empty, so the job store is **not** updated
        
-> `job_run` progress and status are not initialized

Frontend:

- The progress modal asks for the current job status
- https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/templates/angular/admin/plugins/manage_plugins.html#L81
    - `progress` doesn't exist, so `undefined` is printed to the log window
- https://github.com/pencilblue/pencilblue/blob/master/plugins/pencilblue/templates/angular/admin/plugins/manage_plugins.html#L85
    - `status` doesn't exist either, so the `else` path is taken
    
-> Modal is closed down early

Hope this sort of makes sense.

**Pull request merged**
