### PR TITLE
Add Custom Page and Article URL handling to navigation

### PR DESCRIPTION
**Pull request by jclausen**
This pull request uses the custom URL variables from the page and article in the navigation to ensure canonical URL consistency for the site.

### CODE REVIEW

**Comment by jclausen** [comment]
One issue with this pull request:

When updating the URL in the page/article item admin, I went in to add the functionality to automatically update any existing navigation items that use that item.  It seemed like ArticleService was the right place to do this, but pencilblue/controllers/actions/edit_article bypasses ArticleService and uses the DAO for updates to the page/article.  

I didn't want to mess up how you were handling versions with the custom "id" field, as I wasn't familiar (yet) with how that was handled so I left that one out. 

My suggestion would be to have edit_article use the Article service for updates and then add this change to the update() method:

```
ArticleService.prototype.update = function(articleId, fields, options, cb) {   
	var SectionService = new pb.SectionService; 
        if(!pb.utils.isObject(fields)){
                return cb(new Error('The fields parameter is required'));
        }

	var where = pb.DAO.getIdWhere(articleId);
    var content_type = this.getContentType();

	var dao  = new pb.DAO();
	dao.updateFields(content_type, where, fields, options, function(){
		//update the url update if necessary
		SectionService.updateContentUrls(articleId,fields,cb);
	});
};
```
then in SectionService, add this function (untested as of yet):
```
SectionService.updateContentUrls = function(articleId,fields,cb){
	var dao = new pb.DAO();
	dao.updateFields('section',{where:{item:articleId}},{url:fields.url});
	return cb;
}
```

**Comment by blakecallens** [comment]
The navigation uses the permalink for SEO purposes. If a crawler parses out the navigation from the site and doesn't have the permalink, and someone changes the custom URL, it would result in broken links from the search engine until the next crawl is performed.

I'm on board with why you would want to use the vanity URL for the navigation but, since it effects SEO, I would like to see this as a toggle option in the Content Settings in the admin section.

**Comment by blakecallens** [comment]
BTW, @jclausen, I'd be happy to walk you through updating the admin section interface if you'd like.

**Comment by jclausen** [comment]
Thanks Blake. I was actually working on an expanded admin interface that I was going to submit as a plugin (which you could then incorporate in to the core or not), so I've been spending time in there already.
Let me see if I can amend my pull request with an update that incorporates the url option in to the settings and keeps the permalink options.

**Comment by blakecallens** [comment]
Any update on this, @jclausen?

**Comment by jclausen** [comment]
Sorry, Blake.  I was sidetracked with some other issues over the last week.  I'm going to close this pull request and submit a new on on the 4.0 branch, once I upgrade the app that I tested these changes on.  Look for that sometime next week. -J

**Comment by brianhyder** [comment]
No worries. Thanks you for the contribution and let us know if you have any
issues upgrading. We're happy to help.

**Pull request closed without merging**
