### PR TITLE
Feature/509

### PR DESCRIPTION
**Pull request by brianhyder**
Resolves issue #509. Provides the ability to set language preference at any point during the session and from user preference.

### CODE REVIEW

**Comment by blakecallens** [comment]
Everything looks good, except that I had to logout and log back in for my language changes to take effect. Is there a way to instantly do it if you're changing your own settings?

**Comment by brianhyder** [comment]
Should work if you do it through the profile view. I'm guessing forgot to
change it for the admin view

**Comment by blakecallens** [comment]
Yes, worked in profile view. I noticed that reader login is broken. I'm going to fix it.

**Comment by blakecallens** [comment]
Change in plan. It's just broken on your feature branch. Can you look into it?

**Comment by blakecallens** [comment]
Ok, another change in plan. It's broken in both, so I'll fix it in 0.4.1 and you can merge the change.

**Pull request merged**
