### PR TITLE
Dutch translation

### PR DESCRIPTION
**Pull request by jacobsyentl**
Dutch translation for PencilBlue.

### CODE REVIEW

**Comment by blakecallens** [comment]
Thanks for doing this! Is the nl-BE standard for "belgian dutch", or should
it be nl-NL?

**Comment by jacobsyentl** [comment]
Well nl-NL is practically the same as nl-BE. I wrote it like that because I live in Belgium, but it doesn't matter. Both countries speak the same language :)

**Comment by blakecallens** [comment]
If that's the case, can you duplicate the file and also submit a nl-NL.js?
Thanks!

**Comment by brianhyder** [comment]
Please do not duplicate the file. Pb is smart enough to house that locale
based  on the language alone.

**Comment by brianhyder** [comment]
*pick

**Comment by blakecallens** [comment]
My only concern is if, over time, we might want to add Flemish (true nl-BE) separately.

**Comment by brianhyder** [comment]
At that point all you will need is to provide the specific differences. All
other keys will default to the other locale.

**Comment by blakecallens** [comment]
Well, OK then. :)

**Comment by jacobsyentl** [comment]
So I don't need to add an extra file then?

**Comment by blakecallens** [comment]
No, I was mistaken.

**Comment by blakecallens** [comment]
We good to merge this, @brianhyder?

**Pull request merged**
